import { StyleSheet } from 'react-native';

// Values follow the Figma "ROUND TRIP no border" airport picker frames.
export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  grabber: {
    alignSelf: 'center',
    width: 32,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ADB8CD',
    marginTop: 18,
    marginBottom: 8,
  },
  card: {
    marginHorizontal: 15,
    height: 112,
    borderRadius: 16,
    backgroundColor: '#F3E8FF',
    paddingLeft: 41,
    paddingRight: 26,
    justifyContent: 'center',
  },
  backButton: {
    position: 'absolute',
    left: 1,
    top: 1,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardInput: {
    height: 36,
    paddingVertical: 0,
    paddingHorizontal: 0,
    fontSize: 15,
    color: '#182339',
  },
  cardRow: {
    height: 36,
    justifyContent: 'center',
  },
  cardValue: {
    fontSize: 15,
    lineHeight: 20,
    color: '#182339',
  },
  cardPlaceholder: {
    fontSize: 15,
    lineHeight: 20,
    color: '#697691',
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#C5CEDE',
  },
  swapButton: {
    position: 'absolute',
    right: 1,
    top: 40,
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(124,26,238,0.5)',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearButtonBottom: {
    top: 78,
  },
  clearButton: {
    position: 'absolute',
    right: 1,
    top: 2,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingBottom: 24,
  },
  nearbyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9.2,
    marginLeft: 11,
    marginRight: 18,
    paddingLeft: 2,
    paddingTop: 22,
    paddingBottom: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#CCD3E0',
  },
  nearbyTitle: {
    fontSize: 15,
    lineHeight: 20,
    color: '#182339',
  },
  nearbySubtitle: {
    fontSize: 13,
    lineHeight: 16,
    color: '#3E4B64',
  },
  sectionHeading: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '500',
    color: '#182339',
    marginHorizontal: 16,
    marginTop: 18,
    marginBottom: 12,
  },
  recentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginBottom: 8,
  },
  recentChipsRow: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  recentChip: {
    height: 28,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#697691',
    borderRadius: 14,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  recentChipText: {
    fontSize: 15,
    lineHeight: 20,
    color: '#697691',
  },
  emptyText: {
    fontSize: 14,
    color: '#697691',
    textAlign: 'center',
    marginTop: 24,
    paddingHorizontal: 16,
  },
  cityGroup: {
    marginTop: 14,
    marginBottom: 12,
  },
  cityHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginHorizontal: 11,
    paddingHorizontal: 5,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#CCD3E0',
  },
  cityHeaderText: {
    flex: 1,
  },
  cityName: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    color: '#182339',
  },
  cityRegion: {
    fontSize: 13,
    lineHeight: 16,
    color: '#3E4B64',
  },
  airportRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingLeft: 28,
    paddingRight: 20,
    paddingTop: 14,
  },
  airportName: {
    flex: 1,
    fontSize: 13,
    lineHeight: 16,
    color: '#3E4B64',
  },
  airportCode: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '500',
    color: '#182339',
    marginLeft: 16,
  },
});
