import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ECEEF3',
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#182339',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 13,
    color: '#697691',
    textAlign: 'center',
    marginTop: 4,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  flightCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ECEEF3',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  flightCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  flightIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#3D2B85',
    alignItems: 'center',
    justifyContent: 'center',
  },
  flightRoute: {
    fontSize: 15,
    fontWeight: '700',
    color: '#182339',
  },
  flightMeta: {
    fontSize: 12,
    color: '#697691',
    marginTop: 2,
  },
  flightTimeCol: {
    alignItems: 'flex-end',
  },
  flightTime: {
    fontSize: 15,
    fontWeight: '700',
    color: '#182339',
  },
  flightDate: {
    fontSize: 12,
    color: '#697691',
    marginTop: 2,
  },
  legPillRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  legPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ECEEF3',
    borderRadius: 12,
    padding: 12,
  },
  legPillActive: {
    borderColor: '#7C1AEE',
    backgroundColor: '#F3E8FF',
  },
  legPillLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#697691',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  legPillLabelActive: {
    color: '#7C1AEE',
  },
  legPillRoute: {
    fontSize: 14,
    fontWeight: '700',
    color: '#182339',
    marginTop: 4,
  },
  legPillMeta: {
    fontSize: 11,
    color: '#697691',
    marginTop: 2,
  },
  tabRow: {
    flexDirection: 'row',
    borderRadius: 10,
    backgroundColor: '#F7F8FA',
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: '#F3E8FF',
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#697691',
  },
  tabLabelActive: {
    color: '#7C1AEE',
  },
  loadingIndicator: {
    marginVertical: 32,
  },
  emptyStateText: {
    fontSize: 13,
    color: '#697691',
    textAlign: 'center',
    marginVertical: 24,
  },
  ruleCard: {
    borderWidth: 1,
    borderColor: '#ECEEF3',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  ruleName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#182339',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 6,
  },
  ruleDesc: {
    fontSize: 13,
    lineHeight: 20,
    color: '#3E4B64',
  },
  footer: {
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#ECEEF3',
  },
  closeButton: {
    flex: 1,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#7C1AEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: '#7C1AEE',
    fontSize: 15,
    fontWeight: '600',
  },
  gotItButton: {
    flex: 1,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#7C1AEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gotItButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
});
