import { StyleSheet } from 'react-native';

// Matches the Figma My Trips frames (Product → Phone Dev: Upcoming, Completed,
// Cancelled, No upcoming trips, Sort by).
export const PURPLE = '#7C1AEE';
export const INK = '#182339';
export const MUTED = '#6B7891';
export const BORDER = '#D9E1EC';
export const GREEN = '#15803D';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 21,
    paddingRight: 20,
    paddingTop: 27,
    paddingBottom: 0,
  },
  greeting: {
    fontSize: 13,
    lineHeight: 16,
    color: '#697691',
  },
  title: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
    color: INK,
  },
  bellButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#CCD3E0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellDot: {
    position: 'absolute',
    top: 8,
    left: 26,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    backgroundColor: '#C5001F',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 20.5,
    height: 50,
    borderWidth: 1,
    borderColor: '#CCD3E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: INK,
    paddingVertical: 0,
  },
  tabs: {
    flexDirection: 'row',
    marginTop: 15,
    marginHorizontal: 13.5,
    height: 46,
    borderBottomWidth: 2,
    borderBottomColor: '#CCD3E0',
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 11,
  },
  tabText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    color: MUTED,
  },
  tabTextActive: {
    color: PURPLE,
    fontWeight: '700',
  },
  tabUnderline: {
    position: 'absolute',
    bottom: -2,
    height: 4,
    width: 84,
    backgroundColor: PURPLE,
  },
  chips: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    gap: 6,
  },
  chip: {
    height: 32,
    paddingHorizontal: 15,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#98A5BF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipActive: {
    backgroundColor: PURPLE,
    borderColor: PURPLE,
  },
  chipText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '500',
    color: '#3E4B64',
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  listTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: INK,
  },
  sortLink: {
    fontSize: 13,
    lineHeight: 16,
    color: PURPLE,
  },
  listContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  stateText: {
    fontSize: 15,
    color: MUTED,
    textAlign: 'center',
  },
  retryText: {
    marginTop: 12,
    fontSize: 15,
    fontWeight: '600',
    color: PURPLE,
  },

  // --- Trip card
  card: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  typeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#F3EAFE',
  },
  typeChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: PURPLE,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusBadgeText: {
    fontSize: 13,
    fontWeight: '700',
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
  },
  planeTile: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#F3EAFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeText: {
    fontSize: 18,
    fontWeight: '700',
    color: INK,
  },
  dateText: {
    fontSize: 14,
    color: MUTED,
    marginTop: 1,
  },
  carrierRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  carrierText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#3E4B64',
  },
  carrierMuted: {
    fontSize: 14,
    color: MUTED,
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#ECEEF3',
    marginVertical: 12,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  metaLabel: {
    fontSize: 12,
    letterSpacing: 0.4,
    color: MUTED,
  },
  metaValue: {
    fontSize: 15,
    fontWeight: '700',
    color: INK,
    marginTop: 2,
  },
  amountText: {
    fontSize: 20,
    fontWeight: '700',
    color: INK,
    marginTop: 2,
  },
  refundText: {
    fontSize: 15,
    fontWeight: '700',
    color: GREEN,
    marginTop: 2,
  },
  refundPending: {
    fontSize: 15,
    fontWeight: '700',
    color: '#B45309',
    marginTop: 2,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  primaryButton: {
    flex: 1,
    height: 44,
    borderRadius: 8,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  secondaryButton: {
    flex: 1,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PURPLE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: PURPLE,
  },
  halfButton: {
    flex: 0,
    width: '50%',
  },
  rateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
  },
  rateText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: PURPLE,
  },
  helpBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#EEF3FF',
    marginBottom: 14,
  },
  helpTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E3A8A',
  },
  helpText: {
    fontSize: 13,
    color: '#3E4B64',
    marginTop: 2,
  },

  // --- Empty state
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  emptyArt: {
    width: 130,
    height: 130,
    marginBottom: 22.7,
  },
  emptyCircle: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 1,
    borderColor: '#E2C9FF',
    backgroundColor: '#F3E8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: INK,
  },
  emptyText: {
    fontSize: 15,
    color: MUTED,
    textAlign: 'center',
    marginTop: 11.5,
    lineHeight: 20,
    maxWidth: 300,
  },
  emptyButtons: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 23.8,
    marginHorizontal: -7,
    alignSelf: 'stretch',
    justifyContent: 'center',
  },

  // Empty-state buttons: Figma 172 x 46 (1pt border), 12 Bold labels.
  emptyButton: {
    flex: 0,
    width: 172,
    height: 46,
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 8,
  },
  emptyButtonText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },

  // --- Sort sheet
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(24, 35, 57, 0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 28,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: INK,
    textAlign: 'center',
    marginBottom: 8,
  },
  sheetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  sheetOptionText: {
    fontSize: 16,
    color: INK,
  },
  sheetOptionTextActive: {
    color: PURPLE,
    fontWeight: '700',
  },
  sheetClose: {
    height: 48,
    borderRadius: 10,
    backgroundColor: '#F3EAFE',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  sheetCloseText: {
    fontSize: 16,
    fontWeight: '600',
    color: PURPLE,
  },
});
