import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerSafeArea: {
    backgroundColor: '#FFFFFF',
  },
  header: {
    height: 56,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#CCD3E0',
    shadowColor: '#1B3249',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#182339',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
  },
  headerSpacer: {
    width: 44,
  },
  scrollContent: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 32,
  },
  legLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7C1AEE',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  routeCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    marginBottom: 16,
    shadowColor: '#1B3249',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  routeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#3C0D74',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingLeft: 8,
    paddingRight: 9,
    paddingTop: 21,
    paddingBottom: 17,
    marginBottom: -7,
  },
  routeHeaderText: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  routeHeaderDuration: {
    fontSize: 15,
    lineHeight: 24,
    color: '#FFFFFF',
  },
  segmentBlock: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 11.4,
    paddingBottom: 11,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  segmentLeftCol: {
    width: 63,
    alignItems: 'flex-end',
  },
  segmentTimeSlot: {
    alignItems: 'flex-end',
  },
  segmentTime: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600',
    color: '#182339',
  },
  segmentDate: {
    fontSize: 13,
    lineHeight: 18,
    color: '#3E4B64',
  },
  durationSlot: {
    height: 32,
  },
  durationSlotCentered: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  railCol: {
    width: 34,
    alignItems: 'center',
    paddingVertical: 6,
  },
  railDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#3E4B64',
  },
  railLineHalf: {
    flex: 1,
    width: 2,
    backgroundColor: '#C2CADA',
  },
  railPlaneIcon: {
    transform: [{ rotate: '180deg' }],
  },
  segmentRightCol: {
    flex: 1,
  },
  segmentCitySlot: {
    minHeight: 20,
  },
  segmentCity: {
    fontSize: 15,
    lineHeight: 20,
    color: '#182339',
  },
  segmentAirportName: {
    fontSize: 13,
    lineHeight: 18,
    color: '#3E4B64',
  },
  durationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 32,
    gap: 6,
  },
  durationText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#182339',
  },
  carrierBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ECEEF3',
    paddingRight: 8,
  },
  carrierLogo: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F2F3F8',
    borderWidth: 1,
    borderColor: '#DFE3EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carrierName: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#182339',
  },
  layoverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    height: 49,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#E8EDF1',
  },
  layoverText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#182339',
  },
  viewFlightDetailsLink: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    color: '#7C1AEE',
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 11.6,
  },
  noticeBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    backgroundColor: '#FFF3E8',
    borderWidth: 1,
    borderColor: 'rgba(179,98,0,0.1)',
    borderRadius: 12,
    paddingTop: 12,
    paddingBottom: 12,
    paddingHorizontal: 12,
    marginBottom: 12,
    marginRight: 8,
  },
  noticeIcon: {
    width: 16.67,
    height: 16.67,
    borderRadius: 8.33,
    margin: 1.67,
    backgroundColor: '#CE6400',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeText: {
    maxWidth: 270,
    fontSize: 15,
    lineHeight: 20,
    color: '#182339',
  },
  paxBlock: {
    marginBottom: 12,
  },
  selectionHintText: {
    color: '#D9822B',
    fontSize: 13,
    marginBottom: 8,
  },
  travelerCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  travelerCountLabel: {
    fontSize: 15,
    lineHeight: 20,
    color: '#697691',
  },
  travelerCountValue: {
    fontSize: 15,
    lineHeight: 20,
    color: '#697691',
  },
  loadingIndicator: {
    marginVertical: 16,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#697691',
    marginVertical: 12,
  },
  travelerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  travelerRowLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    flex: 1,
  },
  checkbox: {
    width: 20,
    height: 20,
    marginTop: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#ADB8CD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#7C1AEE',
    borderColor: '#7C1AEE',
  },
  travelerName: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: '#182339',
  },
  travelerMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: '#3E4B64',
  },
  travelerAgeNote: {
    fontSize: 12,
    color: '#D9822B',
    marginTop: 2,
  },
  editLink: {
    fontSize: 15,
    lineHeight: 20,
    color: '#3E4B64',
    marginTop: 6,
    marginRight: 32,
  },
  addTravelerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
  },
  addTravelerText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#7C1AEE',
  },
  gstToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
  },
  gstToggleText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#182339',
  },
  gstFields: {
    gap: 10,
    marginBottom: 16,
  },
  gstInput: {
    borderWidth: 1,
    borderColor: '#ADB8CD',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#182339',
  },
  moreButton: {
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#7C1AEE',
    marginTop: 8,
  },
  moreButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7C1AEE',
  },
  allTravelersBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(24, 35, 57, 0.4)',
    justifyContent: 'flex-end',
  },
  allTravelersSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  allTravelersHeader: {
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ECEEF3',
    marginBottom: 12,
  },
  allTravelersTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#182339',
  },
  allTravelersList: {
    maxHeight: 360,
  },
  allTravelersFooter: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 16,
  },
  closeButton: {
    flex: 1,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#7C1AEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: '#7C1AEE',
    fontSize: 15,
    fontWeight: '600',
  },
  addButton: {
    flex: 1,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#7C1AEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  paymentSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#CCD3E0',
  },
  paymentAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentAmountLabel: {
    fontSize: 15,
    lineHeight: 20,
    color: '#182339',
  },
  paymentAmountValue: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: '#6A16CB',
  },
  paymentErrorText: {
    color: '#EF4444',
    fontSize: 13,
    marginBottom: 12,
  },
  payButton: {
    width: 196,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#7C1AEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  payButtonDisabled: {
    backgroundColor: '#CEAAFF',
  },
  payButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
  },
  paymentSuccessBanner: {
    marginTop: 16,
    alignItems: 'center',
    gap: 6,
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#EAFBF1',
  },
  paymentSuccessTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#137A44',
  },
  paymentSuccessSubtitle: {
    fontSize: 13,
    color: '#3E4B64',
    textAlign: 'center',
  },
  routeHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  layoverIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#E8EEFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewFlightDetailsRow: {
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionChips: {
    gap: 5,
    paddingRight: 12,
    marginBottom: 16,
  },
  sectionChip: {
    height: 32,
    paddingHorizontal: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CCD3E0',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  sectionChipText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '500',
    color: '#3E4B64',
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#ECEEF3',
    borderRadius: 12,
    paddingTop: 10.9,
    paddingBottom: 12.8,
    paddingLeft: 12.5,
    paddingRight: 23,
    marginRight: 8,
  },
  gstCard: {
    marginTop: 16,
    marginBottom: 12,
  },
  infoCardText: {
    flex: 1,
  },
  infoCardTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#182339',
    marginBottom: 4.3,
  },
  infoCardSubtitle: {
    fontSize: 15,
    lineHeight: 20,
    color: '#182339',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#CCD3E0',
    marginVertical: 16,
    marginRight: 17,
  },
  noticeIconText: {
    color: '#FFFFFF',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '700',
  },
  travelerInfo: {
    flex: 1,
  },
});
