import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerSafeArea: {
    backgroundColor: '#FFFFFF',
  },
  header: {
    height: 56,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#CCD3E0',
    shadowColor: '#1B3249',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#182339',
    fontSize: 16,
    fontWeight: '700',
  },
  headerSpacer: {
    width: 44,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  legLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7C1AEE',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  routeCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ECEEF3',
    overflow: 'hidden',
    marginBottom: 20,
  },
  routeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#6014B7',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  routeHeaderText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  routeHeaderDuration: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  segmentBlock: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  segmentLeftCol: {
    width: 72,
    alignItems: 'flex-end',
  },
  segmentTimeSlot: {
    alignItems: 'flex-end',
  },
  segmentTime: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#182339',
  },
  segmentDate: {
    fontSize: 11,
    lineHeight: 14,
    color: '#697691',
  },
  durationSlot: {
    height: 32,
  },
  durationSlotCentered: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  railCol: {
    width: 24,
    alignItems: 'center',
  },
  railDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#182339',
  },
  railLineHalf: {
    flex: 1,
    width: 1,
    backgroundColor: '#ADB8CD',
  },
  railPlaneIcon: {
    transform: [{ rotate: '180deg' }],
  },
  segmentRightCol: {
    flex: 1,
  },
  segmentCitySlot: {
    minHeight: 20,
  },
  segmentCity: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: '#182339',
  },
  segmentAirportName: {
    fontSize: 12,
    lineHeight: 16,
    color: '#697691',
  },
  durationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 32,
    gap: 6,
  },
  durationText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#697691',
  },
  carrierBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 15,
    backgroundColor: '#ECEEF3',
    paddingVertical: 3,
    paddingRight: 8,
    paddingLeft: 3,
  },
  carrierLogo: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F2F3F8',
    borderWidth: 1,
    borderColor: '#DFE3EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carrierName: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#182339',
  },
  layoverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#F7F8FA',
  },
  layoverText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#3E4B64',
  },
  viewFlightDetailsLink: {
    fontSize: 14,
    fontWeight: '600',
    color: '#114BFF',
    textAlign: 'center',
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#182339',
    marginBottom: 12,
  },
  noticeBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#FDF1E3',
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
  },
  noticeIcon: {
    marginTop: 2,
  },
  noticeText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: '#8A5A1E',
  },
  travelerCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  travelerCountLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#697691',
  },
  travelerCountValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#697691',
  },
  loadingIndicator: {
    marginVertical: 16,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#697691',
    marginVertical: 12,
  },
  travelerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ECEEF3',
  },
  travelerRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#ADB8CD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#7C1AEE',
    borderColor: '#7C1AEE',
  },
  travelerName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#182339',
  },
  travelerMeta: {
    fontSize: 12,
    color: '#697691',
    marginTop: 2,
  },
  editLink: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7C1AEE',
  },
  addTravelerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 16,
  },
  addTravelerText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7C1AEE',
  },
  paymentSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#ECEEF3',
  },
  paymentAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  paymentAmountLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#697691',
  },
  paymentAmountValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#182339',
  },
  paymentErrorText: {
    color: '#EF4444',
    fontSize: 13,
    marginBottom: 12,
  },
  payButton: {
    height: 48,
    borderRadius: 8,
    backgroundColor: '#7C1AEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  payButtonDisabled: {
    backgroundColor: '#CEAAFF',
  },
  payButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600',
  },
  paymentSuccessBanner: {
    marginTop: 16,
    alignItems: 'center',
    gap: 6,
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#EAFBF1',
  },
  paymentSuccessTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#137A44',
  },
  paymentSuccessSubtitle: {
    fontSize: 13,
    color: '#3E4B64',
    textAlign: 'center',
  },
});
