import { StyleSheet } from 'react-native';

// Values follow the Figma "Select Travellers and class" sheet.
export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  grabber: {
    alignSelf: 'center',
    width: 32,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ADB8CD',
    marginTop: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#CCD3E0',
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginBottom: -1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    color: '#182339',
  },
  content: {
    paddingBottom: 0,
  },
  sectionLabel: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '500',
    color: '#3E4B64',
    marginHorizontal: 16,
    marginTop: 8.8,
    marginBottom: 12.2,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#CCD3E0',
    marginTop: 8,
    marginBottom: 8.3,
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 62,
    paddingLeft: 34,
    paddingRight: 25,
    // Figma: steppers at x 262 / 326 on the 375 frame.
  },
  stepperLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    color: '#182339',
  },
  stepperSubLabel: {
    fontSize: 13,
    lineHeight: 16,
    color: '#3E4B64',
  },
  stepperControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 88,
  },
  stepperButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#CCD3E0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonDisabled: {
    backgroundColor: '#ECEEF3',
  },
  stepperValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: '#182339',
    minWidth: 16,
    textAlign: 'center',
  },
  classGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginHorizontal: 17,
  },
  classButton: {
    height: 28,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#697691',
    borderRadius: 14,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
  },
  classButtonSelected: {
    borderColor: '#7C1AEE',
    backgroundColor: '#F3E8FF',
  },
  classButtonText: {
    fontSize: 15,
    lineHeight: 20,
    color: '#697691',
  },
  classButtonTextSelected: {
    color: '#7C1AEE',
    fontWeight: '500',
  },
  confirmButton: {
    marginLeft: 17,
    marginRight: 15,
    marginTop: 10,
    marginBottom: 16,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#7C1AEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
  },
});
